# Generated by Django 5.1 on 2024-08-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.CharField(max_length=200)),
            ],
        ),
    ]
